server:
  port: 1994

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bloodRequest_db?createDatabaseIfNotExist=true&serverTimezone=UTC&sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

